baseURL = 'https://someoneelshere.github.io/SomeoneElsBlog'
languageCode = 'en-us'
title = 'The SomeoneEls Blog'
theme = 'SomeoneElsTheme'
ignoreLogs = ['warning-goldmark-raw-html']
[markup.goldmark.renderer]
unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
